version: '3.3'
services:
  root-container:
    build:
      dockerfile: Dockerfile

  db-soap-service:
    image: mysql:latest
    ports:
      - 3308:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_USER: root
      MYSQL_HOST: db-soap-service:3306
      MYSQL_DATABASE: saranghaengbok_soap

  # db-php-app:
  #   container_name: db-php-app
  #   image: mysql:latest
  #   ports:
  #     - 6603:3306
  #   volumes:
  #     - ./db:/docker-entrypoint-initdb.d
  #   environment:
  #     MYSQL_ROOT_PASSWORD: admin
  #     MYSQL_ROOT_USER: root
  #     MYSQL_DATABASE: saranghaengbok_php

  # db-rest-service:
  #   container_name: db-rest-service
  #   image: mysql:latest
  #   ports:
  #     - 6605:3306
  #   volumes:
  #     - ./db:/docker-entrypoint-initdb.d
  #   environment:
  #     MYSQL_ROOT_PASSWORD: admin
  #     MYSQL_ROOT_USER: root
  #     MYSQL_DATABASE: saranghaengbok_rest

  # php-app:
  #   extends:
  #     file: ../PHP-App/docker-compose.yml
  #     service: saranghaengbok
  
  soap-services:
    extends:
      file: ../SOAP-Service/docker-compose.yml
      service: soap-service

  # client-spa:
  #   extends:
  #     file: ../client-spa/docker-compose.yml
  #     service: client-spa

  # rest-services:
  #   extends:
  #     file: ../rest-service/docker-compose.yml
  #     service: rest-service


  phpmyadmin:
    container_name: pma_container
    image: phpmyadmin:latest
    restart: always
    links:
    # - db-php-app
    - db-soap-service
    # - db-rest-service
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_PORT=3306
      - PMA_HOSTS=db-php-app, db-soap-service, db-rest-service

volumes:
  # php_app:
  soap_service:
  # rest_service: