version: '3.3'
services:
  root-container:
    build:
      dockerfile: Dockerfile

  db-soap-service:
    image: mysql:latest
    ports:
      - 3308:3306
    volumes:
      - db-soap-service:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: saranghaengbok_soap

  db-php-app:
    image: mysql:latest
    ports:
      - 6603:3306
    volumes:
      - db-php-app:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: saranghaengbok_php

  db-rest-service:
    image: mysql:latest
    ports:
      - 6605:3306
    volumes:
      - db-rest-service:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: saranghaengbok_rest

  php-app:
    extends:
      file: ../PHP-App/docker-compose.yml
      service: php-app
  
  soap-service:
    extends:
      file: ../SOAP-Service/docker-compose.yml
      service: soap-service

  client-spa:
    extends:
      file: ../client-spa/docker-compose.yml
      service: client-spa

  rest-service:
    extends:
      file: ../rest-service/docker-compose.yml
      service: rest-service


  phpmyadmin:
    container_name: pma_container
    image: phpmyadmin:latest
    restart: always
    links:
    - db-php-app
    - db-soap-service
    - db-rest-service
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_PORT=3306
      - PMA_HOSTS=db-php-app, db-soap-service, db-rest-service

volumes:
  db-rest-service:
    # external: true
    # name: db-rest-service
  db-soap-service:
    # external: true
    # name: db-soap-service
  db-php-app:
    # external: true
    # name: db-php-app